Accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path('profile/', views.user_profile, name='user_profile'),
    path('logout/', views.logout_request, name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

WebAppsDjangoProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('CarsManagement.urls')),  # Route for CarsManagement'
    path('booking/', include('Booking.urls')),  # Adjust 'Booking.urls' to your app's name
    path('', include('main.urls')),
    path('accounts/', include('Accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

Accounts/models.py
from django.db import models

# Create your models here.

Booking/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from CarsManagement.models import Car


class Booking(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    transmission_type = models.CharField(max_length=10, choices=(('Automatic', 'Automatic'), ('Manual', 'Manual')),
                                         default='Automatic')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True)
    gps_service = models.BooleanField(default=False)
    additional_requests = models.TextField(blank=True, null=True, default='')
    TRANSMISSION_CHOICES = (
        ('Automatic', 'Automatic'),
        ('Manual', 'Manual'),
    )

    def save(self, *args, **kwargs):
        # Calculate the number of days
        delta = self.end_date - self.start_date
        num_days = delta.days

        # Calculate the price
        self.price = num_days * self.car.price_per_day

        super(Booking, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.user.username}'s booking of {self.car.make} {self.car.model}"

Accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control',
                                                                           'required': 'required',
                                                                           'type': 'email',
                                                                           'placeholder': 'exmaple@email.com',
                                                                           'maxlength': '254', }))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control',
                                               'required': 'required',
                                               'type': 'text',
                                               'placeholder': 'username',
                                               'maxlength': '150', }),
            'password1': forms.PasswordInput(attrs={'class': 'form-control',
                                                    'required': 'required',
                                                    'type': 'password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control',
                                                    'required': 'required',
                                                    'type': 'password'}),
        }

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.is_active = False
        if commit:
            user.save()
        return user

Accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.mail import EmailMessage
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .forms import NewUserForm


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = render_to_string('acc_activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return render(request, 'email_confirmation.html')
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
    else:
        form = NewUserForm()
    return render(request=request, template_name="register.html", context={"register_form": form})


def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
        valid_link = False  # Add a variable to track the validity of the link

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        valid_link = True
    else:
        valid_link = False

    return render(request, 'email_confirmed.html', {'valid_link': valid_link})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    messages.info(request, f"You are now logged in as {username}.")
                    return redirect("home")
                else:
                    messages.error(request, "Your account is not activated.")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="login.html", context={"login_form": form})


@login_required
def user_profile(request):
    xsl_url = staticfiles_storage.url('xsl/booking_template.xsl')
    return render(request, 'user_profile.html', {'xsl_url': xsl_url})


@login_required
def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect("home")

Accounts/templates/acc_activate_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>Hi {{ user.username }},</p>
    <p>Please click on the link below to confirm your registration:</p>
    <a href="http://{{ domain }}{% url 'activate' uidb64=uid token=token %}">Activate</a>
</body>
</html>

Accounts/templates/email_confirmation.html
{% extends "base.html" %} 

{% block content %}
    <div class="container">
        <h2>Registration Confirmation</h2>
        <p>Please confirm your email address to complete the registration.</p>
    </div>
{% endblock %}

Accounts/templates/email_confirmed.html
{% extends "base.html" %} 

{% block content %}
    <div class="container">
        {% if valid_link %}
            <h2>Account Activation Successful</h2>
            <p>Your account has been activated successfully.</p>
        {% else %}
            <h2>Invalid Activation Link</h2>
            <p>The activation link is invalid!</p>
        {% endif %}
    </div>
{% endblock %}

Accounts/templates/login.html
{% extends "base.html" %}
<h1>{% block header %}Login{% endblock %}</h1>
{% block content %}
    <div class="container py-5">
        <form method="POST" class="form-horizontal">
            {% csrf_token %}
            {% for field in login_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Login</button>
        </form>
        <p>Forgot your password? <a href="{% url 'password_reset' %}"> Reset your password</a></p>
        <p class="text-center">Don't have an account? <a href="{% url 'register' %}">Create an account</a>.</p>
    </div>

{% endblock %}

Accounts/templates/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Password Reset Complete{% endblock %}

{% block content %}
    <div class="container">
        <h2>Password Reset Complete</h2>
        <p>Your password has been set. You may go ahead and <a href="{% url 'login' %}">log in</a> now.</p>
    </div>
{% endblock %}

Accounts/templates/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Enter New Password{% endblock %}

{% block content %}
    <div class="container">
        <h2>Enter New Password</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Change my password</button>
        </form>
    </div>
{% endblock %}

Accounts/templates/password_reset_done.html
{% extends "base.html" %}
{% block title %}Password Reset Sent{% endblock %}

{% block content %}
    <div class="container">
        <h2>Password Reset Sent</h2>
        <p>We've emailed you instructions for setting your password, if an account exists with the email you entered.
            You should receive them shortly.</p>
        <p>If you don't receive an email, please make sure you've entered the address you registered with, and check
            your spam folder.</p>
    </div>
{% endblock %}

Accounts/templates/password_reset_form.html
{% extends "base.html" %}
{% block title %}Password Reset{% endblock %}

{% block content %}
    <div class="container">
        <h2>Reset Your Password</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Reset my password</button>
        </form>
    </div>
{% endblock %}

Accounts/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block header %}Register{% endblock %}
{% block content %}
    <div class="container py-5">
        <form method="POST" class="form-horizontal">
            {% csrf_token %}
            {% for field in register_form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button class="btn btn-primary" type="submit">Register</button>
        </form>
        <p class="text-center">If you already have an account, <a href="{% url 'login' %}">login</a> instead.</p>
    </div>
{% endblock %}

Accounts/templates/user_profile.html
{% extends 'base.html' %}

{% block title %}User Profile{% endblock %}
{% block header %}Your Profile{% endblock %}
{% block content %}
    <div class="container">
        <div class="profile-info">
            <h4>Username: {{ user.username }}</h4>
            <h4>Email: {{ user.email }}</h4>
        </div>

        <div class="profile-section">
            <h2>My Bookings</h2>
            <p>
                <a href="{% url 'download_bookings' %}" class="booking-button">Download Bookings</a>
            </p>
            {% if user.booking_set.all %}
                <div class="bookings">
                    {% for booking in user.booking_set.all %}
                        <div class="booking">
                            <h3>
                                Booking: {{ booking.car.make }} {{ booking.car.model }} {{ booking.car.year_of_production }}</h3>
                            <p>Pickup Date: {{ booking.start_date }}</p>
                            <p>Return Date: {{ booking.end_date }}</p>
                            <p>Transmission Type: {{ booking.transmission_type }}</p>
                            <p>Price: ${{ booking.price }}</p>
                            {% if booking.gps_service %}
                                <p>GPS Service: Yes</p>
                            {% else %}
                                <p>GPS Service: No</p>
                            {% endif %}
                            {% if booking.additional_requests == '' %}
                                <p>Additional Requests: None</p>
                            {% else %}
                                <p>Additional Requests: {{ booking.additional_requests }}</p>
                            {% endif %}
                            <!-- Add more booking details here -->
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>You have no bookings.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}